version: "2.4"

services:
  # Ports app
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    ports:
      - "8000:8000"
    volumes:
      - ./:/go/src/ports
    depends_on:
      portsdb:
        condition: service_healthy


  portsdb:
    image: postgres:latest
    ports:
      - '5438:5432'
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: ports
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 10
    volumes:
      - ./postgres:/var/lib/postgresql/data
      - ./sql/ports.sql:/docker-entrypoint-initdb.d/create_tables.sql
